apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-page-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-page
  template:
    metadata:
      labels:
        app: login-page
    spec:
      containers:
      - name: login-page-container
        image: vinnu1487/kub:latest
        ports:
        - containerPort: 80
